#!/bin/sh
set -e

for os in $@; do
  if [ $os != "windows" ]; then
    GOOS=$os golint -set_exit_status $(go list ./... | grep -v vendor)
  else
    GOOS=$os golint -set_exit_status --min_confidence=0.9 $(go list ./... | grep -v vendor)
  fi
done
