// generated by stringer -type=level level.go; DO NOT EDIT

package logging

import "fmt"

const _level_name = "UNKNOWNTRACEDEBUGINFOWARNINGERRORCRITICAL"

var _level_index = [...]uint8{0, 7, 12, 17, 21, 28, 33, 41}

func (i level) String() string {
	if i+1 >= level(len(_level_index)) {
		return fmt.Sprintf("level(%d)", i)
	}
	return _level_name[_level_index[i]:_level_index[i+1]]
}
