// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mackerelio/mackerel-agent/mackerel (interfaces: API)

// Package mockmackerel is a generated GoMock package.
package mockmackerel

import (
	gomock "github.com/golang/mock/gomock"
	checks "github.com/mackerelio/mackerel-agent/checks"
	mackerel "github.com/mackerelio/mackerel-client-go"
	http "net/http"
	reflect "reflect"
)

// MockAPI is a mock of API interface
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// CreateGraphDefs mocks base method
func (m *MockAPI) CreateGraphDefs(arg0 []*mackerel.GraphDefsParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGraphDefs", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGraphDefs indicates an expected call of CreateGraphDefs
func (mr *MockAPIMockRecorder) CreateGraphDefs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGraphDefs", reflect.TypeOf((*MockAPI)(nil).CreateGraphDefs), arg0)
}

// CreateHost mocks base method
func (m *MockAPI) CreateHost(arg0 *mackerel.CreateHostParam) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHost indicates an expected call of CreateHost
func (mr *MockAPIMockRecorder) CreateHost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockAPI)(nil).CreateHost), arg0)
}

// FindHost mocks base method
func (m *MockAPI) FindHost(arg0 string) (*mackerel.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHost", arg0)
	ret0, _ := ret[0].(*mackerel.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHost indicates an expected call of FindHost
func (mr *MockAPIMockRecorder) FindHost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHost", reflect.TypeOf((*MockAPI)(nil).FindHost), arg0)
}

// FindHostByCustomIdentifier mocks base method
func (m *MockAPI) FindHostByCustomIdentifier(arg0 string) (*mackerel.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHostByCustomIdentifier", arg0)
	ret0, _ := ret[0].(*mackerel.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHostByCustomIdentifier indicates an expected call of FindHostByCustomIdentifier
func (mr *MockAPIMockRecorder) FindHostByCustomIdentifier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHostByCustomIdentifier", reflect.TypeOf((*MockAPI)(nil).FindHostByCustomIdentifier), arg0)
}

// PostHostMetricValues mocks base method
func (m *MockAPI) PostHostMetricValues(arg0 []*mackerel.HostMetricValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostHostMetricValues", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostHostMetricValues indicates an expected call of PostHostMetricValues
func (mr *MockAPIMockRecorder) PostHostMetricValues(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostHostMetricValues", reflect.TypeOf((*MockAPI)(nil).PostHostMetricValues), arg0)
}

// PutHostMetaData mocks base method
func (m *MockAPI) PutHostMetaData(arg0, arg1 string, arg2 mackerel.HostMetaData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutHostMetaData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutHostMetaData indicates an expected call of PutHostMetaData
func (mr *MockAPIMockRecorder) PutHostMetaData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutHostMetaData", reflect.TypeOf((*MockAPI)(nil).PutHostMetaData), arg0, arg1, arg2)
}

// ReportCheckMonitors mocks base method
func (m *MockAPI) ReportCheckMonitors(arg0 string, arg1 []*checks.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportCheckMonitors", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportCheckMonitors indicates an expected call of ReportCheckMonitors
func (mr *MockAPIMockRecorder) ReportCheckMonitors(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCheckMonitors", reflect.TypeOf((*MockAPI)(nil).ReportCheckMonitors), arg0, arg1)
}

// RetireHost mocks base method
func (m *MockAPI) RetireHost(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetireHost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetireHost indicates an expected call of RetireHost
func (mr *MockAPIMockRecorder) RetireHost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetireHost", reflect.TypeOf((*MockAPI)(nil).RetireHost), arg0)
}

// SetAdditionalHeader mocks base method
func (m *MockAPI) SetAdditionalHeader(arg0 http.Header) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAdditionalHeader", arg0)
}

// SetAdditionalHeader indicates an expected call of SetAdditionalHeader
func (mr *MockAPIMockRecorder) SetAdditionalHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdditionalHeader", reflect.TypeOf((*MockAPI)(nil).SetAdditionalHeader), arg0)
}

// SetUserAgent mocks base method
func (m *MockAPI) SetUserAgent(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserAgent", arg0)
}

// SetUserAgent indicates an expected call of SetUserAgent
func (mr *MockAPIMockRecorder) SetUserAgent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserAgent", reflect.TypeOf((*MockAPI)(nil).SetUserAgent), arg0)
}

// UpdateHost mocks base method
func (m *MockAPI) UpdateHost(arg0 string, arg1 *mackerel.UpdateHostParam) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHost", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHost indicates an expected call of UpdateHost
func (mr *MockAPIMockRecorder) UpdateHost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHost", reflect.TypeOf((*MockAPI)(nil).UpdateHost), arg0, arg1)
}

// UpdateHostStatus mocks base method
func (m *MockAPI) UpdateHostStatus(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHostStatus indicates an expected call of UpdateHostStatus
func (mr *MockAPIMockRecorder) UpdateHostStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostStatus", reflect.TypeOf((*MockAPI)(nil).UpdateHostStatus), arg0, arg1)
}
