name: Build(Go)
run-name: Build (${{ inputs.os-version }}/${{ inputs.go-version }})

on:
  workflow_call:
    inputs:
      os-version:
        description: 'GitHub-hosted runnners'
        default: ubuntu-22.04
        required: false
        type: string
      run:
        description: 'The commands to run in bash'
        default: go build
        required: false
        type: string
      upload-artifact-path:
        description: >
          A file, directory or wildcard pattern that describes what to upload.
          If empty, the workflow will upload no artifacts.
        default: ''
        required: false
        type: string
      upload-artifact-name:
        description: 'Artifact name'
        default: artifact
        required: false
        type: string

env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  run:
    runs-on: ${{ inputs.os-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        cache: true
        check-latest: true

    - run: ${{ inputs.run }}
      shell: bash

    - if: inputs.upload-artifact-path != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.upload-artifact-name }}
        path: ${{ inputs.upload-artifact-path }}
